### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by DieterKoblenz** [lesleyxyz/python-homewizard-kitchen#2]
Works great with the princess kettle. Are there plans to implement this into one of the known home automation software packages i.e.  HA or Domotics?

**Comment by lesleyxyz** [comment]
Hi @DieterKoblenz,

This is currently integrated in my Home Assistent setup using custom_components.
I'll put it on GitHub later today & update this issue

**Comment by DieterKoblenz** [comment]
Hi Lesley, any update?

**Comment by lesleyxyz** [comment]
Yes, I was looking into this but it stopped working locally due to a dependency mismatch with my module & HomeAssistant.
In the mean time you can check out [this](https://gist.github.com/ghys/ea549402e88876e6daa3ac9aa403ec9f) which @ghys made.

It uses [Homie IoT](https://homieiot.github.io/) which you can integrate into [HomeAssistant](https://github.com/nerdfirefighter/HA_Homie/tree/master)

If I fixed the dependency issue I'll update you as well

**Comment by DieterKoblenz** [comment]
Thank you, I'll look into it!

**Comment by lesleyxyz** [comment]
Hi Dieter,

If you still require a solution, I just released my [HomeAssistant HACS Integration](https://github.com/lesleyxyz/hass-homewizard-kettle/)

Kr,
Lesley

**Comment by DieterKoblenz** [comment]
Thanks Lesley! Awesome.
